Repository B-AROL-O/ble-testsuite, pull requests merged in 2023-10, with the labels that each got.

#29 [FIX]: install.sh: Do not ask user which services to restart
  docs/install-freisa.sh
  docs/install.sh
Labels: bug, hacktoberfest

#34 [FEAT]: Apply changes of PR #33 to install-freisa.sh
  docs/install-freisa.sh
  docs/install.sh
Labels: enhancement

#35 feat:README.md: Section "Install ble-testsuite" is no longer valid
  README.md
Labels: bug, documentation
